### ISSUE TITLE
Studio List - List shows deprecated studios

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1239]
We should filter out deprecated studios from the studio list

**Comment by Stafeeva** [comment]
It is fixed but not deployed!

**Comment by kenjinp** [comment]
@annakristinkaufmann has given feedback that this issues is still unresolved.
